### ISSUE TITLE
Banning `console.log()` is not convenient

### ISSUE THREAD

**Issue by varanthir** [evojam/tslint-rules#31]
`common-functionality.tslint.json` contains:
```
    ...
    "no-console": true,
    ...
```
Banning `console.log()` is not convenient as it's commonly used during development and debugging.
I'd suggest: `"no-console": [true, "error"]`

**Comment by marcinwadon** [comment]
Hey @varanthir,
I'd recommend changing the severity of `no-console` rule from `error` to `warning`. The code will compile but with warning ofc. The question is how to set back the severity during CI

**Comment by akrisu** [comment]
resolved in [#38](https://github.com/evojam/tslint-rules/pull/38)
